version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: postgres_engdados
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: regp2569
      POSTGRES_DB: engdados
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: pipeline_app
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data:
